service: my-first-serverless
provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
        - http:
            path: v2/hello
            method: get

plugins:
  - serverless-offline

custom:
   serverless-offline:
    host: 0.0.0.0
    port: 3000